[pytest]
markers =
    magicc: test requires (the correct version of) MAGICC to run.
    ciceroscm: test requires (the correct version of) CICERO-SCM to run.
    faircicero1x_only: test is specific to FaIR 1.6 and CICERO-SCM v1.x (environment 1).
    faircicero2_only: test is specific to FaIR 2.x and CICERO-SCM v2.x (environment 2).
